flowchart TD
    A(select points niformly ) -->|selected points| B(compute flow at the points)
    B --> |flow| C(compute previous position x_t-1)
    B --> |flow, f| D(compute rotation corrected x'_t)
    C --> |x_t-1| E(compute rotation corrected flow arrow)
    D --> |x'_t| E
    E --> F(select 2 arrows from distanced region)
    F --> |2 corrected flow arrows| G(compute FoE as cross point of 2 arrows)
    G --> |iteratively compute FoE| H(update FoE by RANSAC)
    H --> |FoE, inliers, outliers| I(extract outliers as moving points)